name: SpeedRunners
version: ${project.version}
main: me.speedrunners.SpeedRunners
api-version: 1.16
authors: [ Erick ]
description: A plugin for tracking times, split times, and making teams
commands:
  speedrunners:
    description: main command
    aliases: sr